export const TASK_SAVE_REQUEST = "TASK_SAVE_REQUEST";
export const TASK_SAVE_SUCCESS = "TASK_SAVE_SUCCESS";
export const TASK_SAVE_FAIL = "TASK_SAVE_FAIL";

export const TASK_DELETE_REQUEST = "TASK_DELETE_REQUEST";
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";
export const TASK_DELETE_FAIL = "TASK_DELETE_FAIL";

export const MY_TASK_LIST_REQUEST = "MY_TASK_LIST_REQUEST";
export const MY_TASK_LIST_SUCCESS = "MY_TASK_LIST_SUCCESS";
export const MY_TASK_LIST_FAIL = "MY_TASK_LIST_FAIL";

export const TASK_DETAILS_REQUEST = "TASK_DETAILS_REQUEST";
export const TASK_DETAILS_SUCCESS = "TASK_DETAILS_SUCCESS";
export const TASK_DETAILS_FAIL = "TASK_DETAILS_FAIL";